// protoc  --go_out=.\proto\systempb    .\proto\systempb\*.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v6.30.0
// source: proto/systempb/system.proto

package systempb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息Id
type MsgId int32

const (
	MsgId_Msg_None    MsgId = 0
	MsgId_Msg_NewConn MsgId = 1
)

// Enum value maps for MsgId.
var (
	MsgId_name = map[int32]string{
		0: "Msg_None",
		1: "Msg_NewConn",
	}
	MsgId_value = map[string]int32{
		"Msg_None":    0,
		"Msg_NewConn": 1,
	}
)

func (x MsgId) Enum() *MsgId {
	p := new(MsgId)
	*p = x
	return p
}

func (x MsgId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgId) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_systempb_system_proto_enumTypes[0].Descriptor()
}

func (MsgId) Type() protoreflect.EnumType {
	return &file_proto_systempb_system_proto_enumTypes[0]
}

func (x MsgId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgId.Descriptor instead.
func (MsgId) EnumDescriptor() ([]byte, []int) {
	return file_proto_systempb_system_proto_rawDescGZIP(), []int{0}
}

// 通用消息
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         MsgId                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3,enum=systempb.MsgId" json:"msg_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_systempb_system_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_systempb_system_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_systempb_system_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() MsgId {
	if x != nil {
		return x.MsgId
	}
	return MsgId_Msg_None
}

func (x *Message) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_systempb_system_proto protoreflect.FileDescriptor

var file_proto_systempb_system_proto_rawDesc = string([]byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x70, 0x62,
	0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x70, 0x62, 0x22, 0x45, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x6d, 0x73, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x70, 0x62, 0x2e, 0x4d, 0x73,
	0x67, 0x49, 0x64, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x26,
	0x0a, 0x05, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x73, 0x67, 0x5f, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x73, 0x67, 0x5f, 0x4e, 0x65, 0x77,
	0x43, 0x6f, 0x6e, 0x6e, 0x10, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_systempb_system_proto_rawDescOnce sync.Once
	file_proto_systempb_system_proto_rawDescData []byte
)

func file_proto_systempb_system_proto_rawDescGZIP() []byte {
	file_proto_systempb_system_proto_rawDescOnce.Do(func() {
		file_proto_systempb_system_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_systempb_system_proto_rawDesc), len(file_proto_systempb_system_proto_rawDesc)))
	})
	return file_proto_systempb_system_proto_rawDescData
}

var file_proto_systempb_system_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_systempb_system_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_systempb_system_proto_goTypes = []any{
	(MsgId)(0),      // 0: systempb.MsgId
	(*Message)(nil), // 1: systempb.Message
}
var file_proto_systempb_system_proto_depIdxs = []int32{
	0, // 0: systempb.Message.msg_id:type_name -> systempb.MsgId
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_systempb_system_proto_init() }
func file_proto_systempb_system_proto_init() {
	if File_proto_systempb_system_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_systempb_system_proto_rawDesc), len(file_proto_systempb_system_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_systempb_system_proto_goTypes,
		DependencyIndexes: file_proto_systempb_system_proto_depIdxs,
		EnumInfos:         file_proto_systempb_system_proto_enumTypes,
		MessageInfos:      file_proto_systempb_system_proto_msgTypes,
	}.Build()
	File_proto_systempb_system_proto = out.File
	file_proto_systempb_system_proto_goTypes = nil
	file_proto_systempb_system_proto_depIdxs = nil
}
